### ISSUE TITLE
When loading mtab from browser history after the animation finishes, the UI does not appear

### ISSUE THREAD

**Issue by StrongSand94191** [maxhu08/mtab#10]
# System information
Kubuntu 24.04, Firefox 128.0 flatpak

# Steps to reproduce:
1. Make sure animations are enabled
2. Make sure either the search bar or bookmarks are enabled
3. Either search something in the search bar or click on a bookmark
4. Hit the back button in the browser
5. The UI does not reappear, leaving only the wallpaper

**Comment by maxhu08** [comment]
Sorry, I couldn't reproduce this with firefox. Not sure how I could fix this.

**Comment by StrongSand94191** [comment]
That's weird, it just stopped happening for me.

I'll take it, lol
