### ISSUE TITLE
Add support for new window in Firefox

### ISSUE THREAD

**Issue by timrosu** [maxhu08/mtab#14]
There is no mtab entry in `Homepage and new windows` dropdown menu.
![image](https://github.com/user-attachments/assets/c2a136cd-b62b-4635-8f2e-a6dfb290c23c)

I tried installing it in chromium and have confirmed this only affects Firefox.

**Comment by maxhu08** [comment]
I don't use firefox but I think you could try setting the Homepage to Custom URLS... and then set the url to:

moz-extension://6f0536e9-73fb-4ff0-a847-d227a9bf9b25/index.html

The middle part should be the extension id of the extension. You can make sure you're using the right id by going to the options page which will also have the same extension id like:
moz-extension://6f0536e9-73fb-4ff0-a847-d227a9bf9b25/options.html

Try this and let me know if it works.

**Comment by maxhu08** [comment]
Okay, I think I fixed it: https://github.com/maxhu08/mtab/commit/d50f61f0c0d45c5a2a6af5f69987410167810893

 mtab should automatically be as the homepage in the next release

**Comment by timrosu** [comment]
I added content of the commit into manifest.json in `~/.mozilla/firefox/8bthneou.default-release-1670181121040/extensions/contact@maxhu.dev.xpi` file and it works. Thank you.
