### ISSUE TITLE
how to add an add-on?

### ISSUE THREAD

**Issue by L1nker2** [maxhu08/mtab#15]
hi, can you tell me how to add an add-on? I run the script "bun package-firefox" but I don't understand how to add the add-on from the archive? Is there any way to compile this into a “pix” extension?
I am collecting the UPD from source code because I am changing the language of the months and days of the week, if this can be done from within the installed add-on, I will be glad to know how to do this
I use fedora linux, firefox

**Comment by maxhu08** [comment]
To add the extension on firefox go to about:debugging#/runtime/this-firefox
then click load temporary add-on...
and select the dist folder from the mtab project

**Comment by L1nker2** [comment]
oh thank you very much, it helped me
the extension is just great!
