### ISSUE TITLE
Weird flicker when animations are turned on

### ISSUE THREAD

**Issue by NotAriRay** [maxhu08/mtab#17]
https://github.com/user-attachments/assets/9eb1f10d-0e52-4c19-a814-90e1ab0a4e79

Short flicker happens after animation completes, this was happening on the previous version too.

**Comment by maxhu08** [comment]
I think I fixed, it should be fixed in release 1.3.0

https://github.com/user-attachments/assets/cf98e7cb-c21c-486a-a404-d62be103be9f

**Comment by NotAriRay** [comment]
Yup, seems to have fixed it, keep up the great work man!
