### ISSUE TITLE
Icons preview on readme

### ISSUE THREAD

**Issue by 1belini** [maxhu08/mtab#18]
It would be nice to show what icons can be used to customize the bookmarks, not only the image but it's name as well.
This could be included as a preview section in the readme file.

An example:
 
![2024-07-28-213942_hyprshot](https://github.com/user-attachments/assets/211115e1-a908-4bf5-9f2b-b96e9e5251ce)

**Comment by maxhu08** [comment]
There are over 2000 icons that you can use to customize the bookmarks (from https://remixicon.com). I don't think it would be a good idea to display all of them in a readme file. Also, You can see all the icons on remixicon.com instead which also has a search feature.
