### ISSUE TITLE
Is it possible to have the website icons get them automatically from their favicon.ico

### ISSUE THREAD

**Issue by madhur** [maxhu08/mtab#19]
I have set multiple website bookmarks, but find it hard to differentiate visually.

It is tedious to set the custom icon manually for each of them. It would be great if there is an  option to have the icon fetched from their favicon.ico remove url.

**Comment by maxhu08** [comment]
I think I can with using something like https://www.google.com/s2/favicons?domain={}, but for now if you want favicons automatically, you can try setting bookmarks.type to default which will show the favicons.

**Comment by madhur** [comment]
Thanks
