### ISSUE TITLE
Export configuration to more widely used format

### ISSUE THREAD

**Issue by leart-zuka** [maxhu08/mtab#21]
Would it be possible to export all of the made configurations into a json file of some sort?

**Comment by maxhu08** [comment]
I could do that but that affect existing configs, but that would make older configs fail to import. I could make a converter that converts a mtab config to a json and vice versa instead though, which wouldn't break older configs.

**Comment by leart-zuka** [comment]
Would it be possible to maybe contribute to that myself?
Have never really contributed to an open source project but would love to get started if possible.

**Comment by maxhu08** [comment]
Ok I've add a page that can convert the mtab save format to json and vice versa.
