### ISSUE TITLE
Sorting bookmarks

### ISSUE THREAD

**Issue by Angus-Paillaugue** [maxhu08/mtab#22]
I have a new feature idea : being able to drag and drop bookmarks to sort them.
For now you have to delete and re-create them to add one at the start, so a visual sorting system like drag and drop or just up and down arrows to move bookmark items would be super cool.

**Comment by maxhu08** [comment]
Drag and drop might be a bit difficult, I can add arrows to move the up and down though.

**Comment by maxhu08** [comment]
Ok, I've added up and down arrows to move bookmarks. This should be in the next release.
