### ISSUE TITLE
Favicon doesnt load immediately

### ISSUE THREAD

**Issue by NotAriRay** [maxhu08/mtab#23]
https://github.com/user-attachments/assets/723d08a6-e57e-43a1-b22d-054e9f807f98

Tittle basically, also added a video to clarify the issue

**Comment by maxhu08** [comment]
Not sure how I could fix this, I don't get control over how fast the favicon loads.

**Comment by NotAriRay** [comment]
Maybe loading the page only after the config is fully loaded?

**Comment by maxhu08** [comment]
The config does get loaded first, but it takes time for the javascipt to execute.

**Comment by maxhu08** [comment]
I can make it not load the default mtab logo first but that'll result in no logo for a split second.


Uploading mtab-issue-23.mp4…

**Comment by NotAriRay** [comment]
That's better but I feel like I might be able to fix it, give me a bit lol

**Comment by NotAriRay** [comment]
Nvm this shit too hard

**Comment by maxhu08** [comment]
Ok lol, is the video I shared earlier good then?

**Comment by NotAriRay** [comment]
I mean yeah its better, i'll close the issue with this comment ig
