### ISSUE TITLE
Can't save settings anymore?

### ISSUE THREAD

**Issue by StrongSand94191** [maxhu08/mtab#24]
No matter if I press the save button or use ctrl-S, I never get the popup saying my changes have been saved, and the changes don't take effect :/

**Comment by maxhu08** [comment]
There's probably an error when saving. Try inspect element and go to console and saving again. Let me know what the error is. Not at my computer right now, but I'll try to fix it tomorrow.

**Comment by StrongSand94191** [comment]
Sometimes I get `TypeError: document.querySelector(...) is null` and sometimes I don't get anything

**Comment by maxhu08** [comment]
Make sure title.faviconType has a option selected. If an option doesn't have any button selected, you'll get an error like that.

**Comment by StrongSand94191** [comment]
Thanks!
