### ISSUE TITLE
bookmarks display bug

### ISSUE THREAD

**Issue by dest4590** [maxhu08/mtab#25]
if there are pages in the folder, the folder itself is displayed, but when you click on it, the page is empty:
bookmark: 
![image](https://github.com/user-attachments/assets/75baa937-c38e-4fdc-8e44-d777d811147c)

mtab bookmarks:
![image](https://github.com/user-attachments/assets/a6eff2ba-a857-4991-9a96-7f53e52a6d1f)

when clicked:
![image](https://github.com/user-attachments/assets/986348f3-fd20-452a-9ce4-c9481eb57b7f)

mtab version: 1.3.5

**Comment by maxhu08** [comment]
Okay, I've stopped folders from displaying there.

Is that good, or should I make the folder interactive so you can click on it and show the bookmarks inside the folder?

**Comment by dest4590** [comment]
> Okay, I've stopped folders from displaying there.
> 
> Is that good, or should I make the folder interactive so you can click on it and show the bookmarks inside the folder?

yeah, it'll be fine
