### ISSUE TITLE
Nerd font support?

### ISSUE THREAD

**Issue by pective** [maxhu08/mtab#26]
I wanted to add a bookmark to codeberg, but there's no icon for it in RemixIcon, there is one on Nerd Fonts though. I was wondering if you could add support for the nerd font icons, or maybe just custom text as the icons?

Good work on the extension nonetheless!

**Comment by maxhu08** [comment]
I tried making it so that you can do something like `nf-linux-codeberg` and it would render a icon, but I couldn't figure it out. I might come back to this later though, I got pretty close, I could get the nerd font icons to show up, but for some reason using the class didn't work.

**Comment by pective** [comment]
hat if you could add custom text as an icon? so you can just paste it in?

**Comment by maxhu08** [comment]
I think I got it working with classes, now if you enter somoething like `nf-linux-gentoo` in the iconType it'll look this

![SS2024-08-08_10-06-58](https://github.com/user-attachments/assets/5aa3e650-3db5-486c-815e-bb5e137563c0)
