### ISSUE TITLE
Option to add custom icon url for bookmarks

### ISSUE THREAD

**Issue by xd003** [maxhu08/mtab#28]
I think it would be great if support for custom icon urls is added for the bookmarks. Great work with the project btw, was searching for something like since long time, dunno why didn't anyone took it up :)

**Comment by maxhu08** [comment]
Okay, I've added that.

If you set the iconType to a link like `url-https://.....` it will display a custom icon.

**Comment by xd003** [comment]
@maxhu08 Thanks, upon further using the extension extensively for a day on multiple devices, i have one more suggestions/request.

I don't really know if the rectangular shape around each bookmark is only for aesthetic purposes or it serves some purpose. Especially on my small laptop, it's kinda wasting bit too much screen space. An option to disable that rectangular shape or atleast define it's padding along with ability to change the size of the icons themselves would make it perfect since user can adjust them according to his bookmark count & screen size etc. On using 8-10 bookmarks on my small laptop, i have to kinda move the mouse around way too much to reach from one bookmark to another

**Comment by maxhu08** [comment]
Okay, I added the changing number of bookmarks per row, I'll get to the padding stuff later when I have time, but it's going to take a while.

**Comment by maxhu08** [comment]
I'm going to close this issue since I added the custom icon url but I'll move your suggestions to a new issue.
