### ISSUE TITLE
[Request] Improved default bookmarks type

### ISSUE THREAD

**Issue by Kenste** [maxhu08/mtab#30]
I have a couple points that i would love seeing:

1. Change the look of the default type to the be consistent with the custom one. 
I.e. go from:
![1](https://github.com/user-attachments/assets/4d039601-e130-490c-b2c5-7d593d9442d3)
to: 
![2](https://github.com/user-attachments/assets/b5bd4996-91ec-44e3-bc2f-dbf9dc461a55)

2. Use the name of the bookmark for improved distinction of different bookmarks, similar to how i edited it in the second image. And for the default `bookmark.type` use no `bookmark.color` i guess? The icon should be used from the webpage itself, although i am guessing it should do it and it is bugged for me in the first image (Firefox on Linux Nobara).

3. And in #25 you asked if the bookmark folders should be interactive, which was not implemented. Interactive folders would allow for a clean new tab page with functionally many bookmarks on them. An example of how it could be done would be the [Speed Dial in the Vivaldi Browser](https://help.vivaldi.com/desktop/bookmarks-speed-dial/speed-dials/):
![Vivaldi Speed Dial Folder](https://github.com/user-attachments/assets/83ceea1f-0548-4456-9a9b-4b415ddcc3f8)
or be creative, its up to you :P

**Comment by maxhu08** [comment]
Okay, I think I'm going to add another type like default-2 and make it like how you said, but I'm pretty busy at the moment so you'll probably have to wait a while.

**Comment by maxhu08** [comment]
Okay I've got a decent prototype for it, I still need to add the back button for when you enter a folder and more, but I'm getting close.

https://github.com/user-attachments/assets/233ff45f-39e4-4a8c-b5b6-dad010a66efd

**Comment by maxhu08** [comment]
This has been released, so I'm going to close this issue.

**Comment by Kenste** [comment]
The changes look awesome! 

I did notice, though, that you didn’t end up using the bookmark names for distinction. Especially now with the folders, I still think showing the names could make things a lot clearer at a glance.

Was that a choice you made? Totally cool if so—this is your project, after all! Just wanted to throw it out there again in case it was something that got overlooked.

**Comment by maxhu08** [comment]
I'm planning to add the option to show text soon.
