### ISSUE TITLE
Bookmark animations play twice (sometimes)

### ISSUE THREAD

**Issue by BTD12SA** [maxhu08/mtab#31]
### Description
Bookmark animations sometimes play twice.

### To Reproduce
Enable animations and choose any bookmark animation sometimes before going to the website the bookmark animation plays twice.

### System Info
Fedora 40 workstation
Firefox 129.0
mtab V1.3.8

### Video of the issue
[Screencast from 2024-08-15 02-35-53 (trimmed).webm](https://github.com/user-attachments/assets/05c1552d-2781-4b90-b3d7-8bfe7035925e)

**Comment by maxhu08** [comment]
It should be fixed in release 1.3.9

**Comment by maxhu08** [comment]
This should be fixed now.
