### ISSUE TITLE
Bookmark Icons Flicker During Animation on New Tab Page

### ISSUE THREAD

**Issue by fr0st-iwnl** [maxhu08/mtab#33]
I've noticed that the bookmark icons on the new tab page have started flickering during the animation, which seems to have started after the recent update to `version 1.4.1`. Is this supposed to happen, or could it be a bug?

https://github.com/user-attachments/assets/082624b5-a105-44ef-80f0-eb57434fd930

**Comment by maxhu08** [comment]
Sorry, I can't reproduce this with v1.4.1, I'll try to fix it later but it'll be pretty tough since the flickering isn't happening to me.

**Comment by fr0st-iwnl** [comment]
it's all good man take your time i love the extension it's kinda weird that it started flickering so yeah take your time 👍

**Comment by maxhu08** [comment]
I think I fixed it, when 1.4.2 gets released it should be fixed.

**Comment by fr0st-iwnl** [comment]
It started happening again on `version 1.4.8`

**Comment by maxhu08** [comment]
My bad, I'll probably have it fixed by tomorrow.

**Comment by maxhu08** [comment]
It should be fixed in release v1.4.9
