### ISSUE TITLE
Flickering when opening new tab

### ISSUE THREAD

**Issue by xd003** [maxhu08/mtab#35]
I noticed that whenever i open a new tab, the whole page would kinda flicker for some reason. Do note that i have kept animations off. Here's a screen recording of the same. I think this happens maybe because it reloads or something every time a new tab is opened ?

https://github.com/user-attachments/assets/1a674423-b568-44d6-891c-209ce7088597

mtab v1.4.1
Firefox v129.0.1

**Comment by maxhu08** [comment]
That's how it works.

page loads (gray placeholder) -> wallpaper fetched from extension storage -> set background to wallpaper

There has to be something before the wallpaper gets fetched, as far as I know.

**Comment by xd003** [comment]
> That's how it works.
Is it not possible to somehow cache the background image so that maybe if it happens quickly enough, we might not notice the flickering ?
