### ISSUE TITLE
Slight issue with bookmarks management

### ISSUE THREAD

**Issue by dpaulos6** [maxhu08/mtab#36]
Bookmarks are a bit inconsistent, on if you add more, they seem to stop being able to move up and down, besides the first 2, at least in my case. Below is a short video showing the bookmarks not behaving as expected.

https://github.com/user-attachments/assets/a7b7187f-68e1-4a41-a605-ea5e69c1936c

**Comment by maxhu08** [comment]
Okay, thanks for letting me know.

I'm going to try to fix this soon.

**Comment by maxhu08** [comment]
I think I fixed it.

It should be fixed in the next release.

**Comment by maxhu08** [comment]
This should be fixed in v1.4.3
