### ISSUE TITLE
Some bookmark icons still missing (Firefox)

### ISSUE THREAD

**Issue by bengalbroy** [maxhu08/mtab#38]
Thanks for the update ❤️ however, some of the favicons for the bookmarks in default-blocky are still blank, it only shows a few of them correctly, not all.

**Comment by maxhu08** [comment]
Thanks for letting me know.

I'll try to get this fixed soon.

**Comment by maxhu08** [comment]
I think I fixed it.

You should see the fix in the next release.

**Comment by maxhu08** [comment]
Should be fixed in release 1.4.5.
