### ISSUE TITLE
Open multiple tabs with middle click while mtab stays open

### ISSUE THREAD

**Issue by KLDv21** [maxhu08/mtab#39]
Hi, I really love this extension but I feel like there really needs to be a middle click to open in another tab while still having mtab open, just like the vanilla Firefox homepage. I like to open multiple tabs at once from my homepage and I would definitely appreciate its addition as it is important to my workflow ❤️.

**Comment by maxhu08** [comment]
You can press ctrl-left click to open a bookmark in a new tab and ctrl-enter to open search in a new tab.

Hope this helps.

**Comment by KLDv21** [comment]
Oh didn't know I could ctrl-left click! it sure does the trick but I would love to have middle click to open as I have muscle memorized it 😅.

**Comment by maxhu08** [comment]
Okay, I'm planning to add middle click open soon.

**Comment by maxhu08** [comment]
I added it, should middle click should work in the next release.
