### ISSUE TITLE
Custom search engines

### ISSUE THREAD

**Issue by FluxC0** [maxhu08/mtab#4]
Add an option for custom search engines, so that way people can use their own SearX or Whoogle instances. great application by the way <3

**Comment by FluxC0** [comment]
awesomesauce!

**Comment by maxhu08** [comment]
> I just opened a pull request for this. If it gets merged, users will be able to add their own custom search engine in the next release of the extension.

Thank you, this is will definitely be in the next release (v1.0.9).
