### ISSUE TITLE
Import option is not working

### ISSUE THREAD

**Issue by xd003** [maxhu08/mtab#41]
When i click on import, nothing seems to be happening at all

mtab v1.4.7
Firefox v130.0

**Comment by maxhu08** [comment]
You need to save (ctrl+s) after you import, did you do that?

**Comment by maxhu08** [comment]
I'm going to change it to be import to be import & save now though so it's less confusing.

**Comment by xd003** [comment]
> You need to save (ctrl+s) after you import, did you do that?

Oh didn't knew that, i thought clicking on import with open some sort of input wherein i would have to either select the file to import from

**Comment by maxhu08** [comment]
No, you just need to paste in a config (which you get from pressing the export button).

**Comment by xd003** [comment]
> No, you just need to paste in a config (which you get from pressing the export button).

I see but shouldn't import/export be ideally from/to a file. Normally, someone would use this feature when doing any activity which will clear the data of their browser/machine to restore the backup at a later stage. Using the clipboard for import/export is not something i have seen. Currently, i have to do as follows - 

Export - 
1) Click in export
2) paste the content o a .txt file for proper backup

Import - 
1) Copy the pasted contents into clipboard
2) Click on import

We can make it shorter by doing it the standard way of Import from/Export to a file in single step itself

**Comment by maxhu08** [comment]
I don't think that's possible since I don't think I have the ability to write to file system from a extension.

**Comment by xd003** [comment]
> I don't think that's possible since I don't think I have the ability to write to file system from a extension.

But every other extension that i use which has any sort of configuration does it. Eg. uBlock Origin, Dark Reader etc

**Comment by maxhu08** [comment]
Okay, I'll look into it.

**Comment by maxhu08** [comment]
Importing / Exporting a file looks a bit complicated and might not work as expected on all browsers so I'm going to keep it so that import and export to uses text for now. Also exporting as text works fine since the save doesn't take up that much space.

**Comment by xd003** [comment]
Fair enough
