### ISSUE TITLE
Book mark keybinds - Feature idea

### ISSUE THREAD

**Issue by NamelessBystander** [maxhu08/mtab#43]
Hi there,

I have a feature idea that I’ve found useful in other homepage extensions and would love to see in this one. It would be great if each bookmark could be assigned a key binding (e.g., "1" for the first bookmark, "2" for the second, and so on). This would make navigating bookmarks faster reducing the number of inputs to get to the desired site.

The key bindings would work when the homepage is focused (but not in the search bar), so pressing a number key would directly open the corresponding bookmark instead of initiating a search for the number.

**Comment by maxhu08** [comment]
Okay, I'll add that in the next update

**Comment by maxhu08** [comment]
It's been added in release v1.5.3

**Comment by NamelessBystander** [comment]
This is awesome thanks, it's just what i was thinking.
