### ISSUE TITLE
Bookmarks Not Importing with Config File After Update

### ISSUE THREAD

**Issue by fr0st-iwnl** [maxhu08/mtab#44]
is this supposed to happen? whenever a new version of the mtab extension is released i encounter an issue with importing my old config file while most settings import correctly the bookmarks fail to import this forces me to manually reconfigure my bookmarks every time i update the extension which is a pain

**Comment by maxhu08** [comment]
Right click and inspect, when you import it and it fails do any errors appear in the console?

**Comment by fr0st-iwnl** [comment]
> Right click and inspect, when you import it and it fails do any errors appear in the console?

![image](https://github.com/user-attachments/assets/5a368520-e282-4bee-aff7-91c4c5986324)

**Comment by maxhu08** [comment]
I think that's due to your config not having the newer config options in it, and when it tries to fill in the inputs it gives a error because they're undefined.

**Comment by maxhu08** [comment]
This should fix it. It should be fixed in the next release.
