### ISSUE TITLE
[Feature Request] Support For GIFs to be set as animated wallpaper

### ISSUE THREAD

**Issue by Soham52** [maxhu08/mtab#45]
Currently, setting a GIF as a wallpaper only displays a static image of its first frame. Adding support for animated GIFs as wallpapers would be a fantastic enhancement! It would bring more life and personality to our screens. ^^

**Comment by maxhu08** [comment]
Good idea, I'll try to get that added soon.

**Comment by maxhu08** [comment]
Okay I've added it. You should be able to set wallpaper as gifs in the next release.


https://github.com/user-attachments/assets/3af38cc0-2a30-4be9-afbb-31bdba03cfba
