### ISSUE TITLE
New tab default focus is on address/url bar rather than search bar

### ISSUE THREAD

**Issue by i5-650** [maxhu08/mtab#47]
Hello, 

I'm facing some *minor* issue with mtab: 

If I create a new tab, the default focus is on the address/url bar (the bar at the top of the browser) and not on the search bar. 

I tried changing some firefox settings (see [this reddit post](https://www.reddit.com/r/firefox/comments/hr13c1/how_to_make_firefox_focus_search_bar_instead_of/) for the changes I made) and it doesn't change anything. 

I'm on firefox Version 130.0.1 (64-bit), aarch64, MacOS 15, if it helps you.

Could you do something about it or is it on firefox side ?

**Comment by maxhu08** [comment]
It's a browser issue.

New tab extensions can't control focus. The browser will always focus the address bar first when opening a new tab, and .focus() is just ignored.

Sorry.

**Comment by i5-650** [comment]
No big deal, thanks for the infos
