### ISSUE TITLE
Focus disappears after changing keyboard layout

### ISSUE THREAD

**Issue by Shintifo** [maxhu08/mtab#48]
Hello!

Sometime in my searches I use several languages. If I switch the language the focus on the search bar disappears. I use Firefox 130.0.1 (64-bit).

Hope its possible to fix.

Thx

**Comment by maxhu08** [comment]
How do you switch languages? Can you elaborate or send a video?

**Comment by Shintifo** [comment]
I use the hotkey Win+Space. After each time I switch the language, I need  to use the ActivationKey enabled in mtab settings. Here is the demonstration:
[Screencast From 2024-09-29 13-38-12.webm](https://github.com/user-attachments/assets/f6d7f6e2-237f-4b48-b1fd-6d8b0da103d7)

Btw, I'm using Arch Linux on GNOME 47 with wayland protocol.

**Comment by maxhu08** [comment]
Clicking the input doesn't work? Can you only regain focus of the input using the ActivationKey?

I can't recreate this since I'm not on gnome but this seems to be specific to gnome: https://gitlab.gnome.org/GNOME/mutter/-/issues/2626

**Comment by Shintifo** [comment]
Both clicking the input and ActivationKey works fine (sorry for confusion). The problem I need to manually return the focus to the search bar each time after switching the language (either with ActivationKey or cursor clicking). 

It's rather inconvenience rather than critical bug.  


> this seems to be specific to gnome: https://gitlab.gnome.org/GNOME/mutter/-/issues/2626

The GNOME issue, you shared, is loosing whole window focus. In my case I loose the focus only in mtab search bar. I didn't faced such problem anywhere else. In the url bar and classic Firefox search bar everything works fine.
P.s also that issue appear on XOrg session. I'm using the wayland.

**Comment by maxhu08** [comment]
I think I've fixed it, not sure.

I'm going to release the next verison, lmk if its fixed.
