### ISSUE TITLE
add day number and month number

### ISSUE THREAD

**Issue by delegadissim** [maxhu08/mtab#51]
Hey it would be awesome if you could add the day number and the month number on the custom message. Maybe there is already a way to do it but it doesn't say it on the text.

![image](https://github.com/user-attachments/assets/f69937be-ad5f-47b2-a6d5-53b1b5683bcb)

I was trying to do something like:
Sunday 8 of november of 2024. 
or to just have something like:
 08/11/2024

**Comment by maxhu08** [comment]
Okay, I'll try to get that added in some time soon.

**Comment by maxhu08** [comment]
Okay, I added it.

In the next release, you'll be able to use `\m$` and \d$` to represent that.
