### ISSUE TITLE
Font Styles

### ISSUE THREAD

**Issue by Neo3477** [maxhu08/mtab#52]
Hello everyone, 

can someone tell me the correct spelling for Font Styles. So if you want to switch between Bold Regular or Light. I have already tried the following spellings, but none of them seem to work:

“JetbrainsMono Nerd Font Mono Light”
“JetbrainsMono Nerd Font Mono-Light”
“JetbrainsMono Nerd Font Mono:Light”

I am grateful for any help.

**Comment by maxhu08** [comment]
Sorry, but the font system for mtab is not the best right now.

Here's how to do it:

You need to have the font installed on your system or a url, in your case you need a Jetbrains Mono Nerd Font Light url. (You can use one from https://fonts.google.com/specimen/JetBrains+Mono, I couldn't find a nerd font version sorry). 

then in you need to add that to ui.customCSS

@font-face {
  font-family: "<your font name>";
  src: url("<your url>") format("truetype");
}

Then set the font to the font name you gave it.

**Comment by maxhu08** [comment]
I'm going to add a cleaner way to do this soon.

**Comment by maxhu08** [comment]
Okay, in release 1.6.5 you should be able to set message.font.custom to something like `https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100;1,100&display=swap`

**Comment by maxhu08** [comment]
I'm going to close this issue and assume it has been fixed after the font update.
