### ISSUE TITLE
[FEAT] Cloud Sync

### ISSUE THREAD

**Issue by MyDrift-user** [maxhu08/mtab#53]
How about the ability to sync your configuration to a cloud, be it google cloud, onedrive or/and dropbox.
There are many extensions that offer this setting and I think it would make it easier to use for most users with multiple devices.

**Comment by maxhu08** [comment]
I can look into that. I've never done anything with syncing to the cloud so I don't know if it's possible.

**Comment by maxhu08** [comment]
I think this would overcomplicate the extension, plus there's already a export/import config button. Sorry

**Comment by MyDrift-user** [comment]
No problem, still thanks for considering
