### ISSUE TITLE
Adding Kagi to search engines

### ISSUE THREAD

**Issue by greggh** [maxhu08/mtab#54]
Kagi is my default search engine, and I was hoping you could add it to the list of search engines.

Thanks for the awesome extension.

**Comment by maxhu08** [comment]
How does kagi work, I searched it up and it says it's a paid search engine. I add search engine by changing the search query url like this:

```
    google: `https://www.google.com/search?q=`,
    bing: `https://www.bing.com/search?q=`,
    brave: `https://search.brave.com/search?q=`,
    duckduckgo: `https://duckduckgo.com/?q=`,
    yahoo: `https://search.yahoo.com/search?q=`,
    yandex: `https://yandex.com/search/?text=`,
    startpage: `https://www.startpage.com/sp/search?query=`,
    ecosia: `https://www.ecosia.org/search?q=`
```

I don't know how I could do the same for kagi. If you can tell me how I'll try to implement it.

**Comment by greggh** [comment]
Thanks for the response, Kagi works the same. It just has no ads and isn't spammed with SEO junk. So I love it.

https://kagi.com/search?q=example+search

**Comment by maxhu08** [comment]
Okay, I added it.

Kagi will be part of the list of search engines in the next release. For now, just use the search.useCustomEngine option.
