### ISSUE TITLE
Music Widget [Feature Request]

### ISSUE THREAD

**Issue by Soham52** [maxhu08/mtab#55]
A music widget would be an amazing addition to this extension, bringing an extra layer of enjoyment. Features like 'autoplay on startup,' 'play on demand,' shuffle mode, and volume control could make listening effortless and fun. Adding album art or track details would make the experience even more engaging and visually appealing.

**Comment by maxhu08** [comment]
I was thinking about this but I found it gets complicated when it comes to having multiple new tabs open because they were would multiple songs playing at once and they would be out of sync.

**Comment by Soham52** [comment]
Well, One way to handle the multiple tabs issue could be implementing a global controller/detector that ensures only one instance of music playback is active at a time. This controller could sync across all tabs to avoid conflicts, allowing seamless playback. What do you think?

**Comment by maxhu08** [comment]
I feel like that implementation would end up being messy and overcomplicated and it takes away the from the minimalism of the extension.

**Comment by Soham52** [comment]
I understand the concern about maintaining the extension's minimalism. I'll leave the decision up to you. Thanks for considering anyways ^^
