### ISSUE TITLE
FF Bookmarks disappear when type set to default-blocky (1.6.8)

### ISSUE THREAD

**Issue by hyunwooed** [maxhu08/mtab#56]
Hello! I've been using mtab for a while and it's been fantastic overall.

I recently updated to `version 1.6.8` and noticed that bookmarks that are not in a folder disappear immediately after animations are loaded on the New Tab page when `bookmarks.type` is set to `default-blocky`.

**Version**
mtab version 1.6.8, Firefox 134.0b5, macOS 15.1.1

<img width="816" alt="mtab 1 6 8 bug" src="https://github.com/user-attachments/assets/302977ea-bcc1-4e41-9860-ca5ee1d7c5fa">

**Comment by Kenste** [comment]
I have the same issue, with the added bonus, that animations are played even though I have animations disabled.
I think the `bookmarks.defaultBlockyColor` is also ignored for non folder bookmarks. 

Going into a folder does not trigger the animation and disappearing problem. The color problem still occurs.

https://github.com/user-attachments/assets/a72d7664-8723-4caf-bb5a-0adc771ebfb6

**Comment by maxhu08** [comment]
Sorry about that, should be fixed in the next release. 


https://github.com/user-attachments/assets/a432a6a4-e08e-4286-8f0c-c5ee51575386

**Comment by maxhu08** [comment]
Thanks for catching that

**Comment by maxhu08** [comment]
Let me know if it worked in release 1.6.9

**Comment by hyunwooed** [comment]
> Let me know if it worked in release 1.6.9

Fixed! Thank you 😊
