### ISSUE TITLE
Add FontAwsome

### ISSUE THREAD

**Issue by mcshept** [maxhu08/mtab#57]
Adding FontAwsome as icon library would be great for more variety.

**Comment by maxhu08** [comment]
Are you referring to https://fontawesome.com/download ?

**Comment by maxhu08** [comment]
Okay, I added it

![SS2024-12-10_17-12-40](https://github.com/user-attachments/assets/f105744c-95ee-41b3-b962-9f6ae6efefb8)

**Comment by maxhu08** [comment]
You'll be able to use it in the next release.

**Comment by maxhu08** [comment]
I've added this in release 1.7.2 so I'm going to close this issue.
