### ISSUE TITLE
Add Simple Icons

### ISSUE THREAD

**Issue by Ast3risk-ops** [maxhu08/mtab#58]
It contains way more social network/website/corporate icons than Remix Icons or Font Awesome Brands. It is not available in Nerd Fonts either. It is *only* brands, nothing else.

https://simpleicons.org

https://icon-sets.iconify.design/simple-icons

**Comment by maxhu08** [comment]
Okay, I'll look into that.

**Comment by maxhu08** [comment]
![SS2024-12-14_11-27-28](https://github.com/user-attachments/assets/7bc4a861-ac61-451d-9361-d47453b2f39d)

**Comment by Ast3risk-ops** [comment]
To find icons you can use https://icones.js.org/collection/simple-icons instead, better UX than Iconify.

**Comment by maxhu08** [comment]
I'm going to use https://icones.js.org/collection/simple-icons because it shows the actual name of the icons which the simple icons website doesn't do.

**Comment by Ast3risk-ops** [comment]
> I'm going to use [icones.js.org/collection/simple-icons](https://icones.js.org/collection/simple-icons) because it shows the actual name of the icons which the simple icons website doesn't do.

The official site copies them if the logo or name is clicked I think.

**Comment by maxhu08** [comment]
I think it should be fine as long as it shows the name

**Comment by maxhu08** [comment]
I'm going to close the issue since I've added this in release 1.7.4
