### ISSUE TITLE
Option to set a custom favicon

### ISSUE THREAD

**Issue by StrongSand94191** [maxhu08/mtab#6]
would be cool

**Comment by richmailYT** [comment]
A custom favicon for the new tab?

**Comment by StrongSand94191** [comment]
Yes

**Comment by maxhu08** [comment]
It might be possible, I can try to do it the same way I handled uploading wallpapers, but no promises.

**Comment by maxhu08** [comment]
I've added the ability to set a custom favicon in mtab-v1.3.3

**Comment by StrongSand94191** [comment]
Damn, thanks!
