### ISSUE TITLE
Extension file not found

### ISSUE THREAD

**Issue by crumblepup** [maxhu08/mtab#7]
Since earlier today, every time i open a new tab or try to edit mtab settings, i get a "File not found" error.

![image](https://github.com/user-attachments/assets/db8a044f-f6d5-43bd-8466-4f4f2ed5eef0)

Info about my system:
OS: Arch Linux 6.9.8 arch1-1 (x86-64)
Browser: Firefox 128.0

**Comment by maxhu08** [comment]
My bad, I wrote a build script and I didn't check if it built properly, and it didn't work for me either.

I released v1.2.0 which should work properly now.

Sorry about that !

**Comment by crumblepup** [comment]
I reinstalled the extension, and can confirm everything works properly now.
